spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb-core;MODE=PostgreSQL
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    contexts: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          #URL to Keycloak container.
          issuer-uri: http://localhost:8008/realms/todo-keycloak