FROM keycloak/keycloak:25.0
WORKDIR /
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=password
EXPOSE 8080
EXPOSE 9000
COPY todo-keycloak-realm.json /opt/keycloak/data/import/
ENTRYPOINT /opt/keycloak/bin/kc.sh start-dev --import-realm