server.port: 8080

spring:
  application:
    name: todo-gateway
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/change-list.yml
  profiles:
    default: dev
