server.port: 8085

spring:
  application:
    name: todo-gateway
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/change-list.yml
  profiles:
    default: dev
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
            clientSecret:
            scope: user:email
