#Custom properties
scheme: http
hostname: localhost
vue-port: 4000
vue-prefix: ""
# Update scheme if you enable SSL in vite.config.ts
vue-uri: http://${hostname}:${vue-port}${vue-prefix}
core-port: 8081
core-prefix: /api/v1/todo-lists,/api/v1/users
core-uri: ${scheme}://${hostname}:${core-port}

logging:
  level:
    org:
      springframework:
        cloud.gateway: debug
        http.server: debug
        web: debug

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  ssl:
    enabled: false

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: todos-core
          uri: ${core-uri}
          predicates:
            - Path=${core-prefix}/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
            - SaveSession
            - StripPrefix=2
        - id: vue-ui
          uri: ${vue-uri}
          predicates:
            - Path=${vue-prefix}/**
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb-gateway;MODE=PostgreSQL
    username: sa-gateway
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    contexts: dev
  mvc:
    log-request-details: true
  security:
    oauth2:
      client:
        provider:
          todo-keycloak:
            #URL to Keycloak container.
            issuer-uri: http://localhost:8008/realms/todo-keycloak
        registration:
          #Config to the keycloak client for oauth2 signin--obviously, this stuff should be in keyvaults/secrets when not running local on dev
          keycloak:
            provider: todo-keycloak
            authorization-grant-type: authorization_code
            client-id: todo-keycloak-login
            client-secret: kN9lKzIInbVP9aYas71EhOEdjE3lamrO
            scope: openid
